### ISSUE TITLE
Error:(144) Attribute "rippleColor" has already been defined

### ISSUE THREAD

**Issue by androiddream** [avenwu/support#1]
support design library里已经定义过rippleColor了

**Comment by avenwu** [comment]
en, 是的，support开发的时候design library没出现，针对这个命名冲突，master分支的代码已经在数月前修复了

**Comment by avenwu** [comment]
0.1.1已发布，同步了master分支对该问题的修复

**Comment by androiddream** [comment]
@avenwu 所噶
